on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
  schedule:
    # Schedule to run every day at 9 PM
    - cron: '0 21 * * *'

name: Semgrep

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Semgrep Scan
        run: semgrep scan --config auto --severity ERROR --sarif-output=semgrep.sarif juice-shop/

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
          category: semgrep
