on:
  # This Semgrep workflow will scan the submodule and upload the result to github as Sarif
  # This workflow can be trigger manually, on pull request, on Push and periodically.
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
  schedule:
    # The workflow will be trigger everyday at 21:00
    - cron: '0 21 * * *'
name: Semgrep
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Repo Checkout 
        uses: actions/checkout@v4
        with:
          submodules: recursive
    # The semgrep scan will be run in auto config mode and run rulesets depending on the languages identified
    # Only Highest severity (ERROR) will be show
    # Output will be save in sarif
      - name: Semgrep Scan
        run: semgrep scan --config auto --severity ERROR --sarif-output=semgrep.sarif juice-shop/
    
      - name: Save SARIF results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-results
          path: semgrep.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
          category: semgrep
